# Build libs

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Setup GCC
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest
    - name: Build libraries
      run: make all
